### ISSUE TITLE
Errors found running at  start-api

### ISSUE THREAD

**Issue by dalarworld** [stackery/hello-world-node#1]
I am new to serverless  stickers ... please help ....

When I execute stackery local start-api --stack-name serverless-1 --env-name test --aws-profile default 

I am seeing below error. When I Invoke function it work well without any error.... 

`{"errorType":"Runtime.HandlerNotFound","errorMessage":"index.handler is undefined or not exported","stack":["Runtime.HandlerNotFound: index.handler is undefined or not exported","  `

`D:\project-stackery-serverless\serverless-1\src\getWelcomePage>stackery local start-api --stack-name serverless-1 --env-name test --aws-profile default
Using template at ../../template.yaml
Successfully generated credentials for getWelcomePage
Mounting getWelcomePage at http://127.0.0.1:3000/ [GET]
You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected instantly/automatically. You only need to restart SAM CLI if you update your AWS SAM template
2020-06-20 13:14:02  * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
Invoking index.handler (nodejs12.x)

Fetching lambci/lambda:nodejs12.x Docker container image......
Mounting D:\project-stackery-serverless\serverless-1\src\getWelcomePage\src\getWelcomePage as /var/task:ro,delegated inside runtime container
2020-06-20T07:44:22.833Z        undefined       ERROR   Uncaught Exception      {"errorType":"Runtime.HandlerNotFound","errorMessage":"index.handler is undefined or not exported","stack":["Runtime.HandlerNotFound: index.handler is undefined or not exported","    at Object.module.exports.load (/var/runtime/UserFunction.js:144:11)","    at Object.<anonymous> (/var/runtime/index.js:43:30)","    at Module._compile (internal/modules/cjs/loader.js:1133:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)","    at Module.load (internal/modules/cjs/loader.js:977:32)","    at Function.Module._load (internal/modules/cjs/loader.js:877:14)","    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)","    at internal/main/run_main_module.js:18:47"]}
[32mSTART RequestId: e24e9264-8c51-1346-3826-a942a85cb34b Version: $LATEST[0m
[32mEND RequestId: e24e9264-8c51-1346-3826-a942a85cb34b[0m
[32mREPORT RequestId: e24e9264-8c51-1346-3826-a942a85cb34b     Init Duration: 172.26 ms        Duration: 1.88 ms       Billed Duration: 100 ms Memory Size: 3008 MB    Max Memory Used: 40 MB  [0m
Lambda returned empty body!
Invalid API Gateway Response Keys: {'errorType', 'errorMessage'} in {'errorType': 'Runtime.HandlerNotFound', 'errorMessage': 'index.handler is undefined or not exported'}
<class 'samcli.local.apigw.local_apigw_service.LambdaResponseParseException'>
2020-06-20 13:14:23 127.0.0.1 - - [20/Jun/2020 13:14:23] "[35m[1mGET / HTTP/1.1[0m" 502 -
2020-06-20 13:14:23 127.0.0.1 - - [20/Jun/2020 13:14:23] "[31m[1mGET /favicon.ico HTTP/1.1[0m" 403 -
`

**Comment by dalarworld** [comment]
I found issue I was running command from wrong folder. I shoul be running it from 
`D:\project-stackery-serverless\serverless-1`
